---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: chef/ubuntu-12.04
  - name: ubuntu-14.04
    driver_config:
      box: chef/ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[bjn_logstash]
    attributes: {}