#!/usr/bin/env bash
#
# "multiply TMP_DIR APP_NAME NUM_TIMES QUOTED_CMD" will execute QUOTED_CMD NUM_TIMES in parallel
#

tmp_dir="$1"
app_name="$2"
num_times="$3"
quoted_cmd="$4"

cleanup() {
  trap SIGTERM
  while read -r pid ; do
    echo "Killing process #$pid" 1>&2
    kill -9 $pid
  done < "$tmp_dir/$app_name.*.pid"
  rm "$tmp_dir/$app_name*.pid"
  exit
}

trap 'cleanup' TERM

for i in "$(seq 1 $num_times)" ; do
  echo -n "Running '$app_name' ($i)..." 1>&2
  exec $quoted_cmd &
  echo "$!" > "$tmp_dir/$app_name.$i.pid"
  echo " started process #$!" 1>&2
done
echo "$$" > "$tmp_dir/$app_name.pid"
wait

cleanup()